version: 1.2
workflows:
  - subclass: CWL
    name: Words
    primaryDescriptorPath: workflows/words/main.cwl
    testParameterFiles:
      - workflows/words/inputs.json
    authors:
      - name: Flynn Hembroff
  - subclass: CWL
    name: md5sum
    primaryDescriptorPath: workflows/md5sum/md5-sum.cwl
    testParameterFiles:
      - workflows/md5sum/input.json
  - subclass: CWL
    name: ManyJobs
    primaryDescriptorPath: workflows/manyjobs/manyjobs.cwl
    testParameterFiles:
      - workflows/words/inputs.json
      - workflows/manyjobs/inputs.tiny.json
tools:
  - subclass: CWL
    name: BASIC-CWL-FROM-TUTORIAL
    primaryDescriptorPath: workflows/example/example.cwl
    authors:
      - name: Flynn Hembroff


